### ISSUE TITLE
화면 정의서 작성

### ISSUE THREAD

**Issue by pjhyeok** [codestates-seb/seb39_main_049#11]
### Description
Figma tool을 이용해서 화명 정의서 작성.

### Todo
- [x] 초안 작성.
- [x] backend 팀원들과 공유및 피드백.
- [x] 멘토님 피드백.

### Due Date
- 9/15

### ETC
기타 사항 작성해주세요

**Comment by Inhoob** [comment]
멘토님 피드백 받아서 닫겠습니다
