### ISSUE TITLE
사용자 요구사항 정의서

### ISSUE THREAD

**Issue by klkim1913** [codestates-seb/seb39_main_049#5]
### Description

서비스 기능 정의

### Todo
- [x] 초안 작성
- [x] 파트별 설계 진행후 검토시 같이 검토
- [ ] 멘토님 피드백

### Due Date

- 09/14

### ETC

설계기간동안 계속 검토할것.

**Comment by Inhoob** [comment]
frontend 멘토님은 읽었는데 별 피드백 없으셨습니다. 닫을까요?

**Comment by klkim1913** [comment]
> frontend 멘토님은 읽었는데 별 피드백 없으셨습니다. 백엔드쪽도 상관없으시면 닫아주세요

넵 저희도 특별히 없어서 닫겠습니다!
