### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by yeonkkk** [codestates-seb/seb39_main_049#7]
### Description
ERD 작성

### Todo
- [x] ERD 작성
- [x] 프론트엔드 팀 & 멘토님 피드백 요청 및 확인 
- [x] 피드백 기반으로 ERD 수정

### Due Date
- 09/15

### ETC
초안 작성 후 멘토님 검토 요청

**Comment by klkim1913** [comment]
생성, 수정 시간까지 완료
